### ISSUE TITLE
Play Store description makes no mention of open-source or github.

### ISSUE THREAD

**Issue by jaimet** [alt236/KeyEvent-Display---Android#3]
Hi.

I only install apps for which the source is available, so after I found your app on the Play Store, I read the description but as I found nothing that mentioned that the source was available, I didn't bother installing it and I moved on.

Later, I found your gihub repo and realised that it was for the same app, so I'm now a happy (and grateful) user. ("Thank you very much", btw, for writing this - it's greatly appreciated).

Please update the (Play Store) description to mention that it's "open-source" and/or add a link/pointer to your github repo.

Again, many thanks. J :-)

**Comment by alt236** [comment]
Ooh! Thanks for letting me know. I'll update the store listing.

**Comment by alt236** [comment]
Updated description!
