### ISSUE TITLE
Version tags are missing

### ISSUE THREAD

**Issue by marmistrz** [alt236/KeyEvent-Display---Android#9]
The only tag that is present is for v0.0.4. Could you please add the tag for the version corresponding to the release 1.0.0?

**Comment by alt236** [comment]
Just added it.

Due to very fat fingers, https://github.com/alt236/KeyEvent-Display---Android/releases/tag/v1.0.26 is what is called the 1.0.0 release in the readme.

**Comment by marmistrz** [comment]
Btw did you consider adding your app to F-Droid, the repository of FOSS Android apps?

**Comment by alt236** [comment]
It's something I looked at a few days ago, but I got sidetracked. 
There are a few apps I should be submitting there, but I don't have the time to setup the build recipes at the moment.

**Comment by marmistrz** [comment]
For this app, the default config generated by `fdroid import` should work fine as far as I can see (you'll just need to fill-in the description, possibly setup automatic update based on the git tags if you don't want to update the config every time you release)

Thanks!
